[concourse]
[concourse.web]
localuser = "concourse"
password = "changeme"
external_url = "http://concourse-ci"
bind_port = "80"
session_signing_key = "{{pkg.svc_config_path}}/keys/web/session_signing_key"
tsa_host_key = "{{pkg.svc_config_path}}/keys/web/tsa_host_key"
tsa_authorized_keys = "{{pkg.svc_config_path}}/keys/web/authorized_worker_keys"

[postgres]
host_ip = "localhost"
username = "concourse"
password = "changeme"
database = "concourse"
