[concourse]
[concourse.worker]
work_dir = "/opt/concourse/worker"
# name = "{{sys.member_id}}"
private_key = "keys/worker/worker_key"
garden-dns-proxy-enable = true
baggageclaim_driver="naive"

[concourse.web]
# We'll default to loopback but override it within the run hook to use the details from the bind
tsa_host = ""
tsa_port = ""
public_key = "keys/web/tsa_host_key.pub"
