[concourse]
[concourse.web]
add_local_user = true
localuser = "concourse"
localuser_password = "changeme"
external_url = "http://concourse-ci"
bind_port = "80"
session_signing_key = "keys/web/session_signing_key"
tsa_host_key = "keys/web/tsa_host_key"
tsa_authorized_keys = "keys/web/authorized_worker_keys"
tsa_port = "2222"

# Left blank to prove that the binds are working
[concourse.db]
host_ip = ""
port = ""
username = ""
password = ""
name = ""
